---
# tasks file for dotnet

- include: ubuntu.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install dotnet core
  package:
    name: "{{ dotnet_packages }}"
    state: present
    update_cache: true
  become: yes
