---
- name: Install Dependencies
  apt:
    name: "{{ dotnet_dependencies }}"
    state: present
    update_cache: yes
  become: yes

- name: Download .deb package
  get_url:
    dest: "{{ user_home}}/.cache/packages-microsoft-prod.deb"
    url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb

- name: Install a .deb package
  apt:
    deb: "{{ user_home}}/.cache/packages-microsoft-prod.deb"
  become: yes
