---
- name: Setup Log Server
  hosts: logservers
  vars:
    user_home: '/home/{{ ansible_user }}'
    user_config: '{{ user_home }}/.config'
    user_cache: '{{ user_home }}/.cache'
    promtail_version: 'v2.1.0'

  tasks:
    - name: Install Rsyslog
      ansible.builtin.package:
        state: present
        name: rsyslog
      become: yes

    - name: Copy rsyslog.conf to server
      ansible.builtin.copy:
        dest: /etc/rsyslog..conf
        src: rsyslog.conf
        group: root
        mode: '0644'
        owner: root
      register: result
      become: yes

    - name: Restart Rsyslog service
      ansible.builtin.systemd:
        name: rsyslog
        enabled: yes
        daemon_reload: yes
        state: restarted
      when: result.changed
      become: yes

    - name: Download promtail
      get_url:
        url: https://github.com/grafana/loki/releases/download/{{ promtail_version }}/promtail-linux-amd64.zip
        dest: /tmp/promtail-linux-amd64{{ promtail_version }}.zip
