---
- name: Setup Manjaro
  hosts: localhost
  connection: local
  vars:
    user_home: '/home/{{ ansible_user }}'
    user_config: '{{ user_home }}/.config'
    user_cache: '{{ user_home }}/.cache'

  roles:
    - common
    - role: git
      vars:
        dotfiles_repo: git@github.com:lawrencefej/.dotfiles.git
    - zsh
    - zshplugins
    - python
    - nvm
    - vim
    # - dotnet
    - dev
    - fzf
    # # - certs
