---
- name: Setup Server
  hosts: servers
  vars:
    user_home: '/home/{{ ansible_user }}'
    user_config: '{{ user_home }}/.config'
    user_cache: '{{ user_home }}/.cache'

  roles:
    - setup
    - common
    - users
    - role: git
      vars:
        gitbranch: server
    - zsh
    - zshplugins
    - vim
    - time
    - lsd
    - fzf
    # - certs
    - update

  tasks:
    # - name: Install Guest Agent
    #   package:
    #     state: present
    #     name: qemu-guest-agent
    #   become: yes

    # - name: Enable Guest Agent
    #   systemd:
    #     name: qemu-guest-agent
    #     enabled: yes
    #     state: started
    #   become: yes

    - name: Check if a reboot is needed on all servers
      register: reboot_required_file
      stat:
        path: /var/run/reboot-required
        get_md5: no
      become: yes

    - name: Reboot Server
      reboot:
        msg: 'Reboot initiated by Ansible for kernel updates'
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        # post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
      become: yes

- name: Configure Log Clients
  import_playbook: log.yaml
