---
- name: Setup Server
  hosts: servers
  vars:
    main_user: lawrence
    win_user: Lawrence
    user_home: '/home/{{ main_user }}'
    user_config: '{{ user_home }}/.config'
    user_cache: '{{ user_home }}/.cache'

  tasks:
  - name: Install Guest Agent
    package:
        state: present
        name: qemu-guest-agent
    become: yes

  - name: Enable Guest Agent
    systemd:
        name: qemu-guest-agent
        enabled: yes
        state: started
    become: yes

  roles:
    - setup
    - common
    - users
    - users
    - role: git
      vars:
        gitbranch: server
    - zsh
    - zshplugins
    - vim
    - time
    - lsd
    - fzf
    # - certs
    - update

- name: Configure Log Clients
  import_playbook: log.yaml
