---
- name: Setup Server
  hosts: servers
  vars:
    main_user: lawrence
    win_user: Lawrence
    user_home: '/home/{{ main_user }}'
    user_config: '{{ user_home }}/.config'
    user_cache: '{{ user_home }}/.cache'

  roles:
    - setup
    - common
    - users
    - users
    - git
    - zsh
    - zshplugins
    - vim
    - lsd
    - fzf
    - update
