---
# - name: Setup WSL Test
#   hosts: wsltest
#   vars:
#     main_user: lawrence
#     win_user: Lawrence
#     user_home: "/home/{{ main_user }}"
#     user_config: "{{ user_home }}/.config"
#     user_cache: "{{ user_home }}/.cache"

#   roles:
#     - setup
#     - common
#     - users
#     - users
#     - git
#     - zsh
#     - zshplugins
#     - python
#     - nvm
#     - vim
#     - dotnet
#     - lsd
#     - fzf
#     - update

- name: Setup Server Test
  hosts: servertest
  vars:
    main_user: lawrence
    user_home: "/home/{{ main_user }}"
    user_config: "{{ user_home }}/.config"
    user_cache: "{{ user_home }}/.cache"

  tasks:
  - name: Install Guest Agent
    package:
        state: present
        name: qemu-guest-agent
    become: yes

  - name: Enable guest Agent
    systemd:
        name: qemu-guest-agent
        enabled: yes
        state: started
    become: yes

  roles:
    - setup
    - common
    - users
    - users
    - role: git
      vars:
        gitbranch: server
    - zsh
    - zshplugins
    - vim
    - lsd
    - time
    - fzf
    - update
