---
- name: Setup WSL Test
  hosts: wsltest
  vars:
    main_user: lawrence
    win_user: Lawrence
    user_home: "/home/{{ main_user }}"
    user_config: "{{ user_home }}/.config"
    user_cache: "{{ user_home }}/.cache"

  roles:
    - setup
    - common
    - users
    - users
    - git
    - zsh
    - zshplugins
    - python
    - nvm
    - vim
    - dotnet
    - lsd
    - update

- name: Setup Server Test
  hosts: servertest
  vars:
    main_user: lawrence
    user_home: "/home/{{ main_user }}"
    user_config: "{{ user_home }}/.config"
    user_cache: "{{ user_home }}/.cache"

  roles:
    - setup
    - common
    - users
    - users
    - git
    - zsh
    - zshplugins
    - vim
    - lsd
    - update
