---
- name: Setup WSL
  hosts: computer
  # comment out for remotedev
  connection: local
  vars:
    user_home: '/home/{{ ansible_user }}'
    user_config: '{{ user_home }}/.config'
    user_cache: '{{ user_home }}/.cache'

  roles:
    - setup
    - common
    - users
    - users
    # comment out for remotedev
    - wslssh
    - role: git
      vars:
        dotfiles_repo: git@github.com:lawrencefej/.dotfiles.git
    - zsh
    - zshplugins
    - python
    - nvm
    - vim
    - dotnet
    - lsd
    - dev
    - fzf
    # - certs
    - update

  tasks:
    - name: Symlink .zshenv
      file:
        src: '{{ user_config }}/.dotfiles/zsh/zshenv/computer/ubuntu/.zshenv'
        path: '{{ user_home }}/.zshenv'
        state: link
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
        mode: '0644'
