---
- name: Setup WSL
  hosts: wsl
  # comment out for remotedev
  connection: local
  vars:
    user_home: '/home/{{ ansible_user }}'
    user_config: '{{ user_home }}/.config'
    user_cache: '{{ user_home }}/.cache'

  roles:
    - setup
    - common
    - users
    - users
    # comment out for remotedev
    - wslssh
    - role: git
      vars:
        dotfiles_repo: git@github.com:lawrencefej/.dotfiles.git
    - zsh
    - zshplugins
    - python
    - nvm
    - vim
    - dotnet
    - lsd
    - dev
    - fzf
    # - certs
    - update
