---
# defaults file for removeconfigfiles
user: lawrence
home: "/home/{{ user }}"
config: "{{ home }}/.config"
cache: "{{ home }}/.cache"
zshconfig: "{{ config }}/zsh"
zshcache: "{{ cache }}/zsh"
zsh_history_file: "{{ zshcache }}/.zsh_history"
dotfiles: "{{ config }}/.dotfiles"

config_files:
  - name: .zshrc
    path: "{{ home }}"
  - name: .gitconfig
    path: "{{ home }}"
  - name: .p10k.zsh
    path: "{{ home }}"
  - name: .vimrc
    src: "{{ dotfiles }}/vim"
    path: "{{ home }}"
  - name: .bashrc
    path: "{{ home }}"
