---
- name: Create folders
  file:
    path: "{{ item }}"
    state: directory
    mode: "0744"
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items: "{{ folders }}"

- name: Create files
  copy:
    content: ""
    dest: "{{ item }}"
    force: no
    mode: "0644"
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items: "{{ files }}"

- name: "Install plugins"
  git:
    dest: "{{ item.path }}/{{ item.name }}"
    repo: "{{ item.url }}"
    force: yes
    depth: "1"
  with_items: "{{ plugins }}"

- name: "symlink config files"
  file:
    src: "{{ item.src }}/{{ item.name }}"
    path: "{{ item.path }}/{{ item.name }}"
    state: link
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
  with_items: "{{ config_files }}"

- name: Add distro specifc aliases
  lineinfile:
    path: "{{ home }}/.zshrc"
    regexp: "{{ item.name }}$"
    insertafter: "{{ item.insertafter }}$"
    line: "{{ item.line }}"
  when: ansible_facts['os_family'] == item.family
  with_items: "{{ aliases }}"
