---
- name: "symlink config files"
  file:
    src: "{{ item.src }}/{{ item.name }}"
    path: "{{ item.path }}/{{ item.name }}"
    state: link
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
  with_items: "{{ config_files }}"

- name: Add distro specifc aliases
  lineinfile:
    path: "{{ home }}/.zshrc"
    regexp: "{{ item.name }}$"
    insertafter: "{{ item.insertafter }}$"
    line: "{{ item.line }}"
  when: ansible_facts['os_family'] == item.family
  with_items: "{{ aliases }}"
