---
- name: set gpg key
  apt_key:
    url: 'https://packages.microsoft.com/keys/microsoft.asc'
    state: present
  become: true

- name: add vs code repository
  template:
    src: vscode.list.j2
    dest: /etc/apt/sources.list.d/vscode.list
    group: root
    owner: root
    mode: '0644'
  become: true

# - name: Add VS Code Repository
#   apt_repository:
#     repo: deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main
#     state: present
#   become: yes
#   when: ansible_os_family == 'Debian'

- name: install vscode
  apt:
    name: code
    update_cache: yes
  become: true
