---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
    - name: Example assertion
      assert:
        that: true

    - name: check zsh package status
      package:
        name: zsh
        state: present
      check_mode: yes
      register: pkg_status

    - name: "Test zsh package is installed"
      assert:
        that:
          - not pkg_status.changed
