---
# tasks file for brave

- name: Add Brave GPG apt Key
  apt_key:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    state: present
  become: yes
  when: ansible_os_family == 'Debian'

- name: Add Brave Repository
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main
    state: present
  become: yes
  when: ansible_os_family == 'Debian'

- name: Update apt and install brave browser
  apt:
    state: present
    name: brave-browser
    update_cache: yes
  become: true
  when: ansible_os_family == 'Debian'
