---
# tasks file for git

- name: Install git
  package:
    state: latest
    name: git
    update_cache: true
  become: true

- name: Create config folder
  file:
    path: "{{ item }}"
    state: directory
    mode: "0744"
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
  with_items: "{{ folders }}"

- name: Clone dotfiles for Redhat
  git:
    dest: "{{ user_config }}/.dotfiles"
    repo: "{{ dotfiles_repo }}"
    version: centos
    accept_hostkey: yes
  when: ansible_facts['os_family'] == "RedHat"

- name: Clone dotfiles for Debian
  git:
    dest: "{{ user_config }}/.dotfiles"
    repo: "{{ dotfiles_repo }}"
    version: master
    accept_hostkey: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Check if gitconfig is a link
  stat:
    path: "{{ user_home }}/.gitconfig"
  register: file

- name: Remove gitconfig
  file:
    path: "{{ user_home }}/.gitconfig"
    state: absent
  when: file.stat.exists == true and file.stat.islnk == false

- name: Symlink .gitconfig
  file:
    src: "{{ dotfiles }}/git/.gitconfig"
    path: "{{ user_home }}/.gitconfig"
    state: link
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
    mode: "0644"
