---
# tasks file for git

- name: Install git
  package:
    state: latest
    name: git
    update_cache: true
  become: true

- name: Create config folder
  file:
    path: "{{ item }}"
    state: directory
    mode: "0744"
    owner: "{{ git_user }}"
    group: "{{ git_user }}"
  with_items: "{{ folders }}"

- name: Clone dotfiles
  git:
    dest: "{{ config }}/.dotfiles"
    repo: "{{ dotfiles_repo }}"
    force: yes
    accept_hostkey: yes

- name: Check if gitconfig is a link
  stat:
    path: "{{ user_home }}/.gitconfig"
  register: file

- name: Remove gitconfig
  file:
    path: "{{ user_home }}/.gitconfig"
    state: absent
  when: file.stat.exists == true and file.stat.islnk == false

- name: Symlink .gitconfig
  file:
    src: "{{ dotfiles }}/git/.gitconfig"
    path: "{{ home }}/.gitconfig"
    state: link
    owner: "{{ git_user }}"
    group: "{{ git_user }}"
    mode: "0644"
