---
- name: Add user and set default shell
  user:
    name: '{{ ansible_user }}'
    create_home: yes
    shell: /bin/zsh
    state: present
  become: yes

- name: Add user to wheel group on RedHat systems
  user:
    name: '{{ ansible_user }}'
    groups:
      - wheel
    append: yes
    state: present
    createhome: yes
  become: yes
  when: ansible_facts['os_family'] == "RedHat"

- name: Add user to sudo group on Debian servers
  user:
    name: '{{ ansible_user }}'
    groups:
      - sudo
    append: yes
    state: present
    createhome: yes
  become: yes
  when: ansible_facts['os_family'] == "Debian"
