---
- name: Make sure the folder exists (Debian, Ubuntu)
  file:
    path: /usr/local/share/ca-certificates
    state: directory
  become: yes

# Note that the .crt is actually a .pem renamed
- name: Copy the certificate (Debian, Ubuntu)
  copy:
    src: '{{ cert_path }}/{{ cert_crt }}'
    dest: '/usr/local/share/ca-certificates/{{ cert_crt }}'
  register: result
  become: yes

- name: Update CA Trust (Debian, Ubuntu)
  command: update-ca-certificates
  when: result | changed
  become: yes
