---
- name: Install EPEL on redhat distros
  yum:
    state: present
    name: epel-release
    update_cache: true
  become: true
  when: ansible_facts['os_family'] == "RedHat"

- name: Install RedHat specific packages
  yum:
    state: present
    name: '{{ RedHat_pkgs }}'
    update_cache: true
  become: true
  when: ansible_facts['os_family'] == "RedHat"

- name: Install Debian specific packages
  package:
    state: present
    name: '{{ Debian_pkgs }}'
    update_cache: true
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Install common packages
  package:
    state: present
    name: '{{ pkgs }}'
    update_cache: true
  become: true
