---
# tasks file for common
- name: Install EPEL on redhat distros
  yum:
    state: present
    name: epel-release
    update_cache: true
  become: true
  when: ansible_facts['os_family'] == "RedHat"

- name: Install RedHat specific packages
  yum:
    state: present
    name: "{{ redhat_pkgs }}"
    update_cache: true
  become: true
  when: ansible_facts['os_family'] == "RedHat"

- name: Install Debian specific packages
  yum:
    state: present
    name: "{{ debian_pkgs }}"
    update_cache: true
  become: true
  when: ansible_facts['os_family'] == "Debian"

# - name: Install Distro specific packages
#   yum:
#     state: present
#     name: "{{ Debian_pkgs }}"
#     update_cache: true
#   become: true
#   when: ansible_facts['os_family'] == "Debian"

- name: Install common packages
  package:
    state: present
    name: "{{ pkgs }}"
    update_cache: true
  become: true

# - name: Run lsd
#   command: lsd /
#   register: test
# ignore_errors: yes
# - name: install lsd
#   command: cargo install lsd
#   register: test
#   ignore_errors: yes

- name: test var
  debug:
    var: test
