---
# tasks file for lsd

# - name: Install Cargo
#   package:
#     state: latest
#     name: cargo
#     update_cache: true
#   become: true

# - name: Install Lsd
#   command: cargo install lsd --version 0.17.0
#   register: test
#   changed_when: "'is already installed' not in test.stderr"

- include: ubuntu.yml
  when: ansible_os_family == 'Debian'
