---
- name: Download .deb package
  get_url:
      dest: "{{ user_home}}/.cache/lsd.deb"
      url: https://github.com/Peltoche/lsd/releases/download/0.19.0/lsd_0.19.0_amd64.deb

- name: Install a .deb package
  apt:
    deb: "{{ user_home}}/.cache/lsd.deb"
  become: yes
