---
# tasks file for docker
- name: Install Required packages
  package:
    state: present
    name: '{{ item }}'
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
  become: true
  when: ansible_os_family == 'Debian'

- include: ubuntu.yml
  when: ansible_distribution == 'Linux Mint' or ansible_distribution == 'Ubuntu'

- include: debian.yml
  when: ansible_distribution == 'Debian'

- name: Update apt and install docker-ce
  package:
    state: present
    name: '{{ item }}'
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  become: true

- name: Make sure we have a 'docker' group
  group:
    name: docker
    state: present
  become: yes

- name: Add user to docker group
  user:
    name: '{{ ansible_user }}'
    groups:
      - docker
    append: yes
    state: present
  become: yes

- name: make sure docker is started and enabled
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes
  become: yes

# tasks for docker-compose

- name: Install PIP
  package:
    state: latest
    name: python3-pip
    update_cache: true
  become: true

- name: Install python packages
  pip:
    name: docker-compose
    state: latest
