---
# tasks file for vim

- name: Install Vim
  package:
    state: latest
    name: vim
    update_cache: true
  become: true
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Redhat'

- name: Check if .vimrc is a link
  stat:
    path: '{{ user_home }}/.vimrc'
  register: file

- name: Remove .vimrc
  file:
    path: '{{ user_home }}/.vimrc'
    state: absent
  when: file.stat.exists == true and file.stat.islnk == false

- name: Symlink .vimrc
  file:
    src: '{{ dotfiles }}/vim/.vimrc'
    path: '{{ user_home }}/.vimrc'
    state: link
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0644'

- name: Symlink .vimrc for root
  file:
    src: '{{ dotfiles }}/vim/.vimrc'
    path: '/root/.vimrc'
    state: link
    owner: 'root'
    group: 'root'
    mode: '0644'
  become: true
