---
# tasks file for vim

- name: Install Vim
  package:
    state: latest
    name: vim
    update_cache: true
  become: true

- name: Check if .vimrc is a link
  stat:
    path: "{{ user_home }}/.vimrc"
  register: file

- name: Remove .vimrc
  file:
    path: "{{ user_home }}/.vimrc"
    state: absent
  when: file.stat.exists == true and file.stat.islnk == false

- name: Symlink .vimrc
  file:
    src: "{{ dotfiles }}/vim/.vimrc"
    path: "{{ user_home }}/.vimrc"
    state: link
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
    mode: "0644"
