---
# tasks file for dev

- name: Create dev dirs
  file:
    path: "{{ project_dir }}/{{ item }}"
    state: directory
    mode: "0744"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  with_items: "{{ dev_dirs }}"

- name: Change ansible remote to ssh
  git:
    dest: "{{ project_dir }}/homelab/ansible"
    repo: git@github.com:lawrencefej/ansible.git
    accept_hostkey: yes
