---
# vars file for common
pkgs:
  - wget
  - iperf3
  - curl
  - nmap
  - unzip
  - net-tools
  - htop
  - rsyslog

RedHat_pkgs:
  - bind-utils
  - nfs-utils

Debian_pkgs:
  - dnsutils
  - fzf
  - nfs-common
  - xz-utils
  - python3-apt
  - apt-transport-https
  - ca-certificates
  - gnupg
  - lsb-release
  - python3-pip
  # - bat
