---
# tasks file for wslssh

- name: Check if ssh exists
  stat:
    path: '{{ user_home }}/.ssh/id_rsa'
  register: file

- name: create ssh folder
  file:
    path: '{{ user_home }}/.ssh'
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0700'

- name: copy ssh private key
  copy:
    src: '/mnt/c/Users/{{ ansible_user }}/.ssh/id_ed25519'
    dest: '{{ user_home }}/.ssh/id_rsa'
    remote_src: yes
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '600'

- name: copy ssh public key
  copy:
    src: '/mnt/c/Users/{{ ansible_user }}/.ssh/id_ed25519.pub'
    dest: '{{ user_home }}/.ssh/id_rsa.pub'
    remote_src: yes
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0644'

- name: Create wsl.conf
  template:
    dest: /etc/wsl.conf
    src: wsl.conf.j2
    owner: root
    group: root
    mode: '644'
  become: yes

- name: Create resolv.conf
  template:
    dest: /etc/resolv.conf
    src: resolv.conf.j2
    owner: root
    group: root
    mode: '644'
  become: yes
