---
# tasks file for wslssh

- name: Check if ssh exists
  stat:
    path: "{{ user_home }}/.ssh/id_rsa"
  register: file

- name: copy ssh
  copy:
    src: "/mnt/c/Users/{{ win_user }}/.ssh"
    dest: "{{ user_home }}"
    remote_src: yes
  when: file.stat.exists == false

- name: Set ssh key permission
  file:
    path: "{{ user_home }}/.ssh/id_rsa"
    group: "{{ main_user }}"
    owner: "{{ main_user }}"
    mode: "0600"
