---
# tasks file for wslssh

- name: Check if ssh exists
  stat:
    path: "{{ user_home }}/.ssh/id_rsa"
  register: file

- name: create ssh folder
  file:
    path: "{{ user_home }}/.ssh"
    state: directory
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
    mode: "0700"

  # when: file.stat.exists == false
- name: copy ssh private key
  copy:
    src: "/mnt/c/Users/{{ win_user }}/.ssh/id_rsa"
    dest: "{{ user_home }}/.ssh/id_rsa"
    remote_src: yes
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
    mode: "600"

  # when: file.stat.exists == false
- name: copy ssh public key
  copy:
    src: "/mnt/c/Users/{{ win_user }}/.ssh/id_rsa.pub"
    dest: "{{ user_home }}/.ssh/id_rsa.pub"
    remote_src: yes
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
    mode: "0644"
  # when: file.stat.exists == false
# - name: Set ssh key permission
#   file:
#     path: "{{ user_home }}/.ssh/id_rsa"
#     group: "{{ main_user }}"
#     owner: "{{ main_user }}"
#     mode: "0600"
