---
# tasks file for zshplugins

- name: zshplugins | Install Powerlevel10k
  git:
    dest: "{{ zsh_theme_path }}/powerlevel10k"
    repo: https://github.com/romkatv/powerlevel10k.git
    force: yes
    depth: "1"

- name: zshplugins | Symlink Plugin
  file:
    src: "{{ dotfiles }}/zsh/.p10k.zsh"
    path: "{{ home }}/.p10k.zsh"
    state: link
    owner: "{{ zsh_user }}"
    group: "{{ zsh_user }}"
    mode: "0644"

- name: zshplugins | Install oh-my-zsh plugins
  git:
    dest: "{{ zsh_plugin_path }}/{{ item.name }}"
    repo: "{{ item.repo }}"
    force: yes
    depth: "1"
  with_items: "{{ plugins }}"
